### ISSUE TITLE
command/authorize: set label access to users

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugins-wishlist#11]
**command/authorize:** this had the worst UX but being able to set label access for users. This should also be redone to have better UX, while still allowing arbitrary label name access control.

[See source code](https://github.com/ubiquity/ubiquibot/blob/579c447ce23397d8947e2f3f2a5e665f1c60fedf/src/handlers/comment/handlers/authorize.ts)

**Comment by whilefoo** [comment]
I'm not sure I saw this command used in the real world so I'm not sure what's the intended usage. I know that `assistive-pricing` already has functionality to allow certain users to set certain labels. @0x4007 rfc

**Comment by 0x4007** [comment]
> I'm not sure I saw this command used in the real world so I'm not sure what's the intended usage. I know that `assistive-pricing` already has functionality to allow certain users to set certain labels. @0x4007 rfc

If it has the capability then we can close this.

**Comment by whilefoo** [comment]
[`onLabelChangeSetPricing`](https://github.com/ubiquibot/assistive-pricing/blob/be0f10d44f5f0699e85c70f9542f0037858d2f71/src/handlers/pricing-label.ts#L31) is triggered when a label on the issue gets added/removed, and sets the price label but also calls
[`labelAccessPermissionsCheck`](https://github.com/ubiquibot/assistive-pricing/blob/be0f10d44f5f0699e85c70f9542f0037858d2f71/src/shared/permissions.ts#L7) which checks if the user has permission to set the label otherwise adds/removes it.

**Comment by 0x4007** [comment]
Those don't handle setting the permissions.

**Comment by 0x4007** [comment]
This also raises the question of plugin capability and coupling. Perhaps we should include all the logic in that plugin instead?

**Comment by whilefoo** [comment]
> Those don't handle setting the permissions.

it also [handles](https://github.com/ubiquibot/assistive-pricing/blob/be0f10d44f5f0699e85c70f9542f0037858d2f71/src/handlers/comment.ts#L7) setting the permission
