### ISSUE TITLE
Content Moderation

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/plugins-wishlist#39]
Some partner's may like the idea of having a Profanity Filter plugin which can be easily installed.

Option 1:
- Use regex and string parsing. We could probably find a package/wordlist and parse each comment ourselves.
 
Option 2:
- Use an LLM built for the purpose of content moderation or any LLM sufficient with the task.

Plugin Specification:
- It should run on every comment event for both `created` and `edited`
- It could edit-in-place the comment, replacing the word(s) with words from a list of author-defined and potentially partner-defined replacements which could make things fun and interesting
- It could simply hide/delete the contributor's comment and post a warning message, this could be configurable too
- It should be configurable such that a partner can decide 'If they break this rule 5 times, we ["limit interactions"](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository)' meaning the user cannot interact with the org for however long the partner configured

Future features:
- It could be expanded to process everything from comments to commits to labels and issue titles

**Comment by 0x4007** [comment]
I don't think this is necessary because 

1. We never had this problem 
2. GitHub is generally used as a work environment and people generally don't communicate in this manner in work environments 
3. GitHub has capabilities to handle problem contributors like deleting or blocking comments. 

Automation is only necessary if the problem happens frequently and regularly. You only need to block once to solve the problem.

**Comment by Keyrxng** [comment]
I see your points yeah. I envisioned Telegram/Discord mod-bots but for GitHub, every web3 partner will use similar bots on those platforms although yeah the atmosphere tends to differ between those and GitHub
